### ISSUE TITLE
Slack Team For our community

### ISSUE THREAD

**Issue by youknowriad** [algeriatech/awesome-algeria#7]
Hi folks!

I've created a slack team for us to talk and communicate. You can ask for an invite here:

https://algeriatech.now.sh

I'll update this link soon with a custom domain.

Please feel free to join, share, tweet, invite friends etc... But just one thing let's keep things organized :)

Talk to you soon on the channel

**Comment by youknowriad** [comment]
@IOAyman

**Comment by IOAyman** [comment]
Oh man you stole that from my mind ;)
I had created a Slack team few months back to gather the community, pretty much the same reason, but did not have time to announce and publish it to people, so I thought it is time I do just yesterday 😉 

Great idea!

**Comment by youknowriad** [comment]
I'm closing, it's a thing now
